In [2]:
import numpy as np
import matplotlib.pyplot as plt

#生成随机矩阵
arr1=np.random.rand(3,2)
print(arr1)

[[0.20238086 0.93113532]
 [0.71452458 0.40564642]
 [0.4569982  0.54938516]]


In [2]:
arr2=np.random.rand(3,2,4)
print(arr2)

[[[0.23687627 0.19938817 0.84477923 0.5096447 ]
  [0.69119396 0.97330095 0.66684785 0.84609316]]

 [[0.67290984 0.76582579 0.45957755 0.70151552]
  [0.84126641 0.49737255 0.42676384 0.89840264]]

 [[0.33368606 0.06161586 0.74987785 0.11848081]
  [0.00751836 0.74043803 0.09762556 0.87294058]]]


In [3]:
zt1=np.random.randn(10,1)
print(zt1)
np.linspace

[[ 0.99773702]
 [-1.23403476]
 [-0.12663622]
 [-2.79386947]
 [ 0.66570479]
 [ 0.11862897]
 [ 0.13321163]
 [-0.23888661]
 [ 0.05246222]
 [ 1.29240838]]
