In [6]:
'''
NumPy(Numerical Python) 是科学计算基础库，提供大量科学计算相关功能，比如数据
统计，随机数生成等。其提供最核心类型为多维数组类型（ndarray），支持大量的维度数组
与矩阵运算，Numpy 支持向量处理 ndarray 对象，提高程序运算速度。
那么Numpy到底有什么功能呢？其实Numpy的功能非常多，主要用于数组计算。Numpy
可以让用户在 Python 语言中使用向量和数学矩阵。

1.将数组或嵌套的数列数据转为n维的ndarray对象
    numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
        object 数组或嵌套的数列
        dtype 数组元素的数据类型，可选
        copy 对象是否需要复制，可选
        order 创建数组的样式，C 为行方向，F 为列方向，A 为任意方向（默认）
        subok 默认返回一个与基类类型一致的数组
        ndmin 指定生成数组的最小维度
2.ndarray对象的shape属性可以获取数组的维度和各个维度元素的数量，值为一个元组对象
    shape[i]返回指定维度的元素数量
    
'''
import numpy as np
list1=[x for x in range(10)]
arr1=np.array(list1)
print(list1)
print(arr1)
print(arr1.shape)
print(arr1.shape[0])
print('---'*5)
arr2=np.array(list1,ndmin=2)
print(arr2)
print(arr2.shape)
print(arr2.shape[0])



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
(10,)
10
---------------
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
1


In [10]:
#将二维数组转为ndarray
list22=[[1,2],[3,4]]
arr22=np.array(list22,ndmin=2)
print(arr22)
print(arr22.shape)

[[1 2]
 [3 4]]
(2, 2)


In [13]:
#ndarray支持切片
arr22=np.array([[1,2,3],[4,5,6]],ndmin=2)
arr221=arr22[0:2,0:2]
print(arr221)
print(arr221.shape)

[[1 2]
 [4 5]]
(2, 2)


In [14]:
#arange 函数创建ndarray对象:numpy.arange(start, stop, step, dtype)
#arange 函数只能创建一维数组
nn1=np.arange(1,10)
print(nn1)

[1 2 3 4 5 6 7 8 9]


In [21]:
import pandas as pd
import numpy as np
r1=np.arange(0,12)
print(type(r1),r1)
r11=r1.reshape(3,4)
print(r11)
df=pd.DataFrame(r11,index=list('xyz'),columns=list('mnkl'))





<class 'numpy.ndarray'> [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


m  n   k   l
x  0  1   2   3
y  4  5   6   7
z  8  9  10  11

In [22]:
#np.nan表示空值
df1=pd.DataFrame([[1,2,np.nan],[3,np.nan,]])
df1

0    1   2
0  1  2.0 NaN
1  3  NaN NaN

In [23]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       2 non-null      int64  
 1   1       1 non-null      float64
 2   2       0 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 180.0 bytes


In [24]:
df1.isnull()

0      1     2
0  False  False  True
1  False   True  True

In [27]:
df1[df1.isnull()]

0   1   2
0 NaN NaN NaN
1 NaN NaN NaN

In [28]:
df1[df1.notnull()]

0    1   2
0  1  2.0 NaN
1  3  NaN NaN